### ISSUE TITLE
hey jack

### ISSUE THREAD

**Issue by RealGsus** [JackCeparou/JackCeparouCompass#3]
don't know if you get this, but since the forum is dead, i thought this might be a way to reach you. 

was wondering if you got any word from KJ or anything?

best regards,
gsus

**Comment by RuneBarrett** [comment]
I too am very interested in any updates if they exist. :)

![tumblr_nv5cbb8tcw1uc7va9o1_500](https://cloud.githubusercontent.com/assets/7199742/24099058/d6166a9a-0d6d-11e7-91ee-770eac59fb39.gif)

**Comment by RealGsus** [comment]
Do you guys think finderskeepers could become a thing now that THUD is R.I.P. and KJ's gone MIA? (http://www.finderskeepersd3.com/)

**Comment by JackCeparou** [comment]
Gosh, just see this xD

I guess everyone got the [new home](http://www.ownedcore.com/forums/diablo-3/turbohud/) ; )
