### ISSUE TITLE
ItemsAndInventoryConfigurator

### ISSUE THREAD

**Issue by kingzleshe** [JackCeparou/JackCeparouCompass#6]
Hello jack:
I enabled sell darkening in ItemsAndInventoryConfigurator.cs , it makes my eyes feel better :)
How do I disable the red mark on the up-left?  It's very annoying and I don't even know what it stands for.

![_20190220102030](https://user-images.githubusercontent.com/20214409/53061662-40318900-34f9-11e9-891b-0893399587a8.png)

**Comment by JackCeparou** [comment]
I think that's [this line](https://github.com/JackCeparou/JackCeparouCompass/blob/master/Customize/Default/ItemsAndInventoryConfigurator.cs#L41)

**Comment by kingzleshe** [comment]
> I think that's [this line](https://github.com/JackCeparou/JackCeparouCompass/blob/master/Customize/Default/ItemsAndInventoryConfigurator.cs#L41)

It worked, thanks jack.
