### ISSUE TITLE
mini elite bar V8.0

### ISSUE THREAD

**Issue by kingzleshe** [JackCeparou/JackCeparouCompass#7]
Hi jack:

As the screenshot shows. I already have elite bar plugin. so that I wish to disable the mini elite bar.
Because this function is a nightmare for party game.
![_20190304101447](https://user-images.githubusercontent.com/20214409/53707095-609e0380-3e68-11e9-984e-d9a7aaaba972.png)

**Comment by JackCeparou** [comment]
Well, looks like you are using the MonsterPack plugin.

`Hud.TogglePlugin<MonsterPackPlugin>(false);` should do the trick (not tested)

Btw, this is a default plugin customization question, you should ask on OC ;)

**Comment by kingzleshe** [comment]
After I tested it.  It does not work.
I think it is not MonsterPack plugin, this issue only happens when I use your latest file on this repositories :(
